name: fununifrac
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9, <3.10
  - pip
  - setuptools
  - blist
  - pip:
    - scipy
    - networkx
    - numpy
    - pandas
    - pyemd
    - matplotlib
    - pytest
    - sparse
    - requests
    - seaborn

