A_MATRIX__FILE_NAME = 'fununifrac_A.npz'
A_MATRIX_BASIS__FILE_NAME = 'fununifrac_A_basis.txt'
EDGE_LIST_OUT__FILE_NAME = 'fununifrac_edge_lengths_{0}.csv'
FUNUNIFRAC_OUT__MAIN_FILE_NAME = 'fununifrac_out_{0}.main.npy'
FUNUNIFRAC_OUT__MAIN_BASIS__FILE_NAME = 'fununifrac_out_{0}.main.basis.npy'
FUNUNIFRAC_OUT__DIFFAB_FILE_NAME = 'fununifrac_out_{0}.diffab'
FUNUNIFRAC_OUT__DIFFAB_NODES_FILE_NAME = 'fununifrac_out_{0}.diffab.nodes.npy'
FUNUNIFRAC_OUT__PUSH_FILE_NAME = 'fununifrac_out_{0}.push.pkl'